const maskify = require('./katas/maskify')
const solution = require('./katas/divisor')
const { printerError } = require('./katas/printer-errors')
const abc123 = require('./katas/abc123')
const summation = require('./katas/summation')
const mm = require('./katas/maxMultiple')
const duplicateEncoder = require('./katas/duplicate-encoder')
const tto = require('./katas/two-to-one')
